/** Served from `public/`; generated by `npm run pack-advisor` (runs before production build). */
export const POKER_LOCAL_ADVISOR_ZIP_HREF = '/poker-local-advisor.zip';

export const POKER_LOCAL_ADVISOR_NIGHTLY_ZIP_HREF = '/poker-local-advisor-nightly.zip';

/** Update manifest for the local advisor self-update feature (same pack script). */
export const POKER_LOCAL_ADVISOR_MANIFEST_HREF = '/poker-local-advisor-manifest.json';

/** Matches `DEFAULT_POKER_ADVISOR_UPDATE_ORIGIN` in `tools/poker-local-advisor/update.mjs` (CLI default when env unset). */
export const POKER_ADVISOR_DEFAULT_UPDATE_ORIGIN = 'https://retro-scope.lovable.app';
