// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';
import { currentEnvironment } from '@/config/environment';

// Use environment-specific configuration
const SUPABASE_URL = currentEnvironment.supabaseUrl;
const SUPABASE_PUBLISHABLE_KEY = currentEnvironment.supabaseAnonKey;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

export const currentEnv = currentEnvironment.environment;
